### ISSUE TITLE
py-mcwsの最新版のリリースの件につきまして

### ISSUE THREAD

**Issue by inunosinsi** [HRTK92/py-mcws#3]
先日プルリクを送った者です。
先日の修正分に問題なければ、pip install py-mcwsで修正版をインストールできるようにして頂けないでしょうか。

私は京都でプログラミング教室をしています。
Chromebook版のマイクラのリリースに合わせて、ChromebookでPythonでマイクラができることを打ち出したい時と思った時にpy-mcwsのプロジェクトを発見しました。

他言語のサンプルコードと比較して、シンプルな構造でいろいろできる事に感銘を受けまして、下記のページのように紹介文の作成を始めました。
https://saitodev.co/microbit/chromebook/article/57

次の記事を書く時にpy-mcwsの新しいバージョンが出ていれば、記事中でpy-mcwsの修正から始めようといったコンテンツを追加する必要がなくなります。

ご検討の程、宜しくお願い致します。

**Comment by HRTK92** [comment]
今、[修正版](https://pypi.org/project/py-mcws/1.1.0/)をリリースしました。
遅れてしまいすいません。このプロジェクトを見つけて貢献してくださりありがとうございます！

**Comment by inunosinsi** [comment]
リリースをありがとうございます。

**Comment by inunosinsi** [comment]
最新の更新内容を拝見致しました。
更新内容に合わせてpy-mcwsの紹介記事を修正致しました。
https://saitodev.co/microbit/chromebook/article/57

一応報告まで
